### ISSUE TITLE
ma_lines plugin fails to build on Fedora 25 x64 with GCC 6.3.1

### ISSUE THREAD

**Issue by euspectre** [euspectre/racehound#4]
Perhaps, something changed significantly in the GCC plugin API between GCC 5.x and 6.x.

Build error:
<pre>
[ 60%] Building CXX object ma_lines/CMakeFiles/ma_lines.dir/ma_lines.cpp.o
/home/eugene/work/RaceHound/racehound/ma_lines/ma_lines.cpp: In function ‘void output_ma_location(gimple, EAccessType)’:
/home/eugene/work/RaceHound/racehound/ma_lines/ma_lines.cpp:105:39: error: cannot convert ‘gimple’ to ‘const gimple*’ for argument ‘1’ to ‘location_t gimple_location(const gimple*)’
  location_t loc = gimple_location(stmt);
                                       ^
/home/eugene/work/RaceHound/racehound/ma_lines/ma_lines.cpp: In function ‘void process_function_call(gimple_stmt_iterator*)’:
/home/eugene/work/RaceHound/racehound/ma_lines/ma_lines.cpp:177:24: error: conversion from ‘gimple*’ to non-scalar type ‘gimple’ requested
  gimple stmt = gsi_stmt(*gsi);
                ~~~~~~~~^~~~~~
/home/eugene/work/RaceHound/racehound/ma_lines/ma_lines.cpp:178:39: error: no matching function for call to ‘gimple_call_fndecl(gimple&)’
  tree fndecl = gimple_call_fndecl(stmt);
                                       ^
In file included from /home/eugene/work/RaceHound/racehound/ma_lines/common_includes.h:39:0,
                 from /home/eugene/work/RaceHound/racehound/ma_lines/ma_lines.cpp:21:
/usr/lib/gcc/x86_64-redhat-linux/6.3.1/plugin/include/gimple.h:3060:1: note: candidate: tree_node* gimple_call_fndecl(const gcall*)
 gimple_call_fndecl (const gcall *gs)
 ^~~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-redhat-linux/6.3.1/plugin/include/gimple.h:3060:1: note:   no known conversion for argument 1 from ‘gimple’ to ‘const gcall*’
/usr/lib/gcc/x86_64-redhat-linux/6.3.1/plugin/include/gimple.h:3066:1: note: candidate: tree_node* gimple_call_fndecl(const gimple*)
 gimple_call_fndecl (const gimple *gs)
 ^~~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-redhat-linux/6.3.1/plugin/include/gimple.h:3066:1: note:   no known conversion for argument 1 from ‘gimple’ to ‘const gimple*’
/home/eugene/work/RaceHound/racehound/ma_lines/ma_lines.cpp: In function ‘void process_expr(gimple_stmt_iterator, tree, bool)’:
/home/eugene/work/RaceHound/racehound/ma_lines/ma_lines.cpp:194:24: error: conversion from ‘gimple*’ to non-scalar type ‘gimple’ requested
  gimple stmt = gsi_stmt(gsi);
                ~~~~~~~~^~~~~
/home/eugene/work/RaceHound/racehound/ma_lines/ma_lines.cpp:210:20: error: cannot convert ‘bool’ to ‘int*’ for argument ‘8’ to ‘tree_node* get_inner_reference(tree, long int*, long int*, tree_node**, machine_mode*, int*, int*, int*, bool)’
   &volatilep, false);
                    ^
/home/eugene/work/RaceHound/racehound/ma_lines/ma_lines.cpp: In function ‘void process_gimple(gimple_stmt_iterator*)’:
/home/eugene/work/RaceHound/racehound/ma_lines/ma_lines.cpp:253:22: error: no match for ‘operator=’ (operand types are ‘gimple’ and ‘gimple*’)
  stmt = gsi_stmt(*gsi);
                      ^
In file included from /home/eugene/work/RaceHound/racehound/ma_lines/common_includes.h:39:0,
                 from /home/eugene/work/RaceHound/racehound/ma_lines/ma_lines.cpp:21:
/usr/lib/gcc/x86_64-redhat-linux/6.3.1/plugin/include/gimple.h:213:3: note: candidate: constexpr gimple& gimple::operator=(const gimple&)
   gimple
   ^~~~~~
/usr/lib/gcc/x86_64-redhat-linux/6.3.1/plugin/include/gimple.h:213:3: note:   no known conversion for argument 1 from ‘gimple*’ to ‘const gimple&’
/usr/lib/gcc/x86_64-redhat-linux/6.3.1/plugin/include/gimple.h:213:3: note: candidate: constexpr gimple& gimple::operator=(gimple&&)
/usr/lib/gcc/x86_64-redhat-linux/6.3.1/plugin/include/gimple.h:213:3: note:   no known conversion for argument 1 from ‘gimple*’ to ‘gimple&&’
/home/eugene/work/RaceHound/racehound/ma_lines/ma_lines.cpp:255:25: error: cannot convert ‘gimple’ to ‘const gimple*’ for argument ‘1’ to ‘bool is_gimple_call(const gimple*)’
  if (is_gimple_call(stmt)) {
                         ^
/home/eugene/work/RaceHound/racehound/ma_lines/ma_lines.cpp:258:32: error: cannot convert ‘gimple’ to ‘const gimple*’ for argument ‘1’ to ‘bool is_gimple_assign(const gimple*)’
  else if (is_gimple_assign(stmt) && !gimple_clobber_p(stmt)) {
                                ^
/home/eugene/work/RaceHound/racehound/ma_lines/ma_lines.cpp:258:59: error: cannot convert ‘gimple’ to ‘const gimple*’ for argument ‘1’ to ‘bool gimple_clobber_p(const gimple*)’
  else if (is_gimple_assign(stmt) && !gimple_clobber_p(stmt)) {
                                                           ^
/home/eugene/work/RaceHound/racehound/ma_lines/ma_lines.cpp:259:26: error: cannot convert ‘gimple’ to ‘const gimple*’ for argument ‘1’ to ‘bool gimple_store_p(const gimple*)’
   if (gimple_store_p(stmt)) {
                          ^
/home/eugene/work/RaceHound/racehound/ma_lines/ma_lines.cpp:260:37: error: no matching function for call to ‘gimple_assign_lhs(gimple&)’
    tree lhs = gimple_assign_lhs(stmt);
                                     ^
In file included from /home/eugene/work/RaceHound/racehound/ma_lines/common_includes.h:39:0,
                 from /home/eugene/work/RaceHound/racehound/ma_lines/ma_lines.cpp:21:
/usr/lib/gcc/x86_64-redhat-linux/6.3.1/plugin/include/gimple.h:2432:1: note: candidate: tree_node* gimple_assign_lhs(const gassign*)
 gimple_assign_lhs (const gassign *gs)
 ^~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-redhat-linux/6.3.1/plugin/include/gimple.h:2432:1: note:   no known conversion for argument 1 from ‘gimple’ to ‘const gassign*’
/usr/lib/gcc/x86_64-redhat-linux/6.3.1/plugin/include/gimple.h:2438:1: note: candidate: tree_node* gimple_assign_lhs(const gimple*)
 gimple_assign_lhs (const gimple *gs)
 ^~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-redhat-linux/6.3.1/plugin/include/gimple.h:2438:1: note:   no known conversion for argument 1 from ‘gimple’ to ‘const gimple*’
/home/eugene/work/RaceHound/racehound/ma_lines/ma_lines.cpp:263:32: error: cannot convert ‘gimple’ to ‘const gimple*’ for argument ‘1’ to ‘bool gimple_assign_load_p(const gimple*)’
   if (gimple_assign_load_p(stmt)) {
                                ^
/home/eugene/work/RaceHound/racehound/ma_lines/ma_lines.cpp:264:38: error: no matching function for call to ‘gimple_assign_rhs1(gimple&)’
    tree rhs = gimple_assign_rhs1(stmt);
                                      ^
In file included from /home/eugene/work/RaceHound/racehound/ma_lines/common_includes.h:39:0,
                 from /home/eugene/work/RaceHound/racehound/ma_lines/ma_lines.cpp:21:
/usr/lib/gcc/x86_64-redhat-linux/6.3.1/plugin/include/gimple.h:2483:1: note: candidate: tree_node* gimple_assign_rhs1(const gassign*)
 gimple_assign_rhs1 (const gassign *gs)
 ^~~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-redhat-linux/6.3.1/plugin/include/gimple.h:2483:1: note:   no known conversion for argument 1 from ‘gimple’ to ‘const gassign*’
/usr/lib/gcc/x86_64-redhat-linux/6.3.1/plugin/include/gimple.h:2489:1: note: candidate: tree_node* gimple_assign_rhs1(const gimple*)
 gimple_assign_rhs1 (const gimple *gs)
 ^~~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-redhat-linux/6.3.1/plugin/include/gimple.h:2489:1: note:   no known conversion for argument 1 from ‘gimple’ to ‘const gimple*’
ma_lines/CMakeFiles/ma_lines.dir/build.make:62: recipe for target 'ma_lines/CMakeFiles/ma_lines.dir/ma_lines.cpp.o' failed
make[2]: *** [ma_lines/CMakeFiles/ma_lines.dir/ma_lines.cpp.o] Error 1
CMakeFiles/Makefile2:581: recipe for target 'ma_lines/CMakeFiles/ma_lines.dir/all' failed
make[1]: *** [ma_lines/CMakeFiles/ma_lines.dir/all] Error 2
</pre>
